/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "jysclyoznivbpdwgdgjr"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imp5c2NseW96bml2YnBkd2dkZ2pyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ1MzY5NzUsImV4cCI6MjA3MDExMjk3NX0.YvDaGt2QutOaF-m_ziTfrUjheS-HFzPkMiwYSNKi_ck"